Improve bootstrap -- identical to bootstrap scripts in applications and libraries
svn path=/trunk/; revision=12606

diff --git a/buildsupport/bootstrap b/buildsupport/bootstrap
--- a/buildsupport/bootstrap
+++ b/buildsupport/bootstrap
@@ -1,21 +1,29 @@
 #!/bin/sh -
 # This is not a starconf bootstrap file
 
-if test -f configure -a configure -nt configure.ac; then
-    : nothing to do
+# If STAR_SUPPRESS_AUTORECONF is true in the environment, then we
+# suppress the call of `autoreconf'.  This is here _only_ so that the top-level
+# bootstrap file can suppress multiple calls of this in bootstrap scripts
+# in its children.  This mechanism must not be used by users, as it is
+# likely to change without warning.
+: ${STAR_SUPPRESS_AUTORECONF=false}
+if $STAR_SUPPRESS_AUTORECONF; then
+    echo "Suppressing autoreconf"
 else
-    autoreconf
-fi
-if test ! -x configure; then
-    echo "Ooooh dear, autoreconf didn't work -- I can't find ./configure"
-    exit 1
+    echorun autoreconf --install --symlink
+
+    if test ! -x configure; then
+        echo "Ooooh dear, autoreconf didn't work -- I can't find ./configure"
+        exit 1
+    fi
 fi
 
-for d in `autoconf --trace=AC_CONFIG_SUBDIRS:$% configure.ac` ''
+thisdir=`basename $PWD`
+for d in `autoconf --trace=AC_CONFIG_SUBDIRS:$% configure.ac` DUMMY
 do
-    if test -n "$d"; then
-        echo "Bootstrapping $d..."
-        (cd $d; ./bootstrap)
+    if test -n "$d" -a -d "$d"; then
+        echo "Bootstrapping $thisdir/$d..."
+        (cd $d && ./bootstrap)
     fi
 done
 
