update-modules: improve checking
Add a test for directory existence and make sure that the repository
being checked is the expected submodule one, not that of the superproject.
If the submodule repository is broken or missing that gets its own
error message.

diff --git a/update-modules b/update-modules
--- a/update-modules
+++ b/update-modules
@@ -34,7 +34,7 @@
 #     In extreme circumstances when you do not have any changes to preserve
 #     the "-f" flag can be used to skip all safety checks.
 #
-#     It is necessary that this script be ran at least once after a 
+#     It is necessary that this script be ran at least once after a
 #     repository clone is created. This will be done by the bootstrap
 #     script.
 
@@ -86,7 +86,7 @@ else
 fi
 
 #  Get a summary of the submodules. If this returns any content then one or
-#  more have been modified and/or committed and may need to be pushed or reset 
+#  more have been modified and/or committed and may need to be pushed or reset
 #  before proceeding. Could also mean that the module just needs updating.
 
 summary=`git submodule summary $submodule`
@@ -102,7 +102,7 @@ if test "$check" = "1" -a "$summary" != ""; then
             #  Submodule is modified. Either internally, needs an update
             #  or could be missing.
             if test -d $path; then
-               #  We want to check internally, ask submodule if it has the 
+               #  We want to check internally, ask submodule if it has the
                #  requested SHA as its head, if not it needs an update.
                if GIT_DIR=$path/.git git rev-parse --verify $sha1^0 >/dev/null 2>&1; then
                   #  Modified, and contains the SHA already, must be a local
@@ -120,9 +120,8 @@ if test "$check" = "1" -a "$summary" != ""; then
             fi
          fi
       done
-   status="$?"
-   if test "$status" != "0"; then 
-      #  Last (sub-shell) command exited in error. So stop.
+   if test "$?" != "0"; then
+      #  Last command in sub-shell exited in error. So stop.
       exit 1
    fi
 fi
@@ -132,10 +131,11 @@ fi
 #  so refuse to proceed when they are present as well.
 
 if test "$submodule" = ""; then
-   #  Get a list of all the paths to the submodules. 
+   #  Get a list of all the paths to the submodules.
    submodule_list="`git config -f .gitmodules --get-regexp '.*\.path$' | awk '{print $2}'`"
 else
-   submodule_list="$submodule" 
+   submodule_list="$submodule"
+
    #  Verify this a submodule, which may not be initialised yet.
    found="`git config -f .gitmodules --get-regexp ".*${submodule}\.path$" | awk '{print $2}'`"
    if test "$found" = ""; then
@@ -147,20 +147,39 @@ fi
 if test "$check" = "1"; then
    for m in $submodule_list; do
 
-      #  May not be checked in yet, in that case we see the modified files in
-      #  the full repository. Avoid that case.
-      nfiles=`cd $m && ls -a | wc -w`
-      if test $nfiles -gt 2 ; then
-         (cd $m && git diff) >/dev/null 2>&1 ; # XXX hack need to update submodule index?
-         modified=`cd $m && git diff-index --name-status HEAD`
-         if test "$modified" != ""; then
-            echo "ERROR: submodule has modified files, not updating anything"
-            echo "... $m"
-            echo "$modified" | head
-            exit 1
+      if test -d "$m"; then
+
+         #  May not be checked in yet, so no repository in place. Check that
+         #  by counting the files, must be more than ". ..", if this is a 
+         #  submodule.
+         nfiles=`cd $m && ls -a | wc -w`
+         if test $nfiles -gt 2 ; then
+            (cd $m && git diff) >/dev/null 2>&1 ; # XXX hack need to update submodule index?
+
+            #  Check for local modifications. Force this command to use the
+            #  submodule repository, not the current one. If this is really a
+            #  repository that is OK, otherwise (i.e bad repository, none
+            #  repository files present) an error will occur.
+            modified=`cd $m && git --git-dir .git diff-index --name-status HEAD 2>&1`
+            if test "$?" != "0"; then
+               echo "ERROR: submodule repository query failed, not updating anything"
+               echo "... $m"
+               echo "    $modified"
+               exit 1
+            fi
+            if test "$modified" != ""; then
+               echo "ERROR: submodule has modified files, not updating anything"
+               echo "... $m"
+               echo "    $modified" | head
+               exit 1
+            fi
+         else
+            echo "... $m requires initialisation"
          fi
-      else
-         echo "... will initialise submodule: $m"
+      else 
+         echo "ERROR: submodule directory is missing, not updating anything"
+         echo "... $m"
+         exit 1
       fi
    done
 fi
