Substantially simplified (which is a pity, because make-starconf.in   was _so_ cunning) starconf.in now only has to deal with one file -- bootstrap --   and this might as well be handled as a special case, avoiding the   generality in make-starconf.in. starconf.m4.in is now installed in `aclocal --print-ac-dir`, where   aclocal expects to find it (putting files in this location is how   libtool makes its macros available).  This avoids the gymnastics hitherto   required, and now updating starconf requires you to remake and   install starconf, then simply rerun autoreconf/bootstrap in the   target directory. The starconf version number is now 1.1
svn path=/trunk/; revision=13898

diff --git a/buildsupport/starconf/Makefile.am b/buildsupport/starconf/Makefile.am
--- a/buildsupport/starconf/Makefile.am
+++ b/buildsupport/starconf/Makefile.am
@@ -1,4 +1,5 @@
 ## Process this file with automake to produce Makefile.in
+
 bin_SCRIPTS = starconf starconf-validate starconf-finder
 pkgdata_DATA = \
 	componentinfo.dtd \
@@ -10,26 +11,8 @@ pkgdata_DATA = \
 # The above files aren't automatically included in clean targets.
 # Files starconf and starconf.m4 should be, however, since they're both
 # files generated by make.
-CLEANFILES=starconf make-starconf starconf.m4
-
-# Include (possibly) required files in the starconf script.
-#     starconf.m4               to add Starlink autoconf macros;
-#     bootstrap                 standardised bootstrap script
-#
-# make-starconf allows filenames to be preceded by options `-xxx'.
-# Option q: files which are _not_ thus prefixed are always unpacked; files
-# with the `q' are unpacked only if starconf detects certain features
-# in the configure.ac, or if the file needs to be updated.
-#
-# Filenames preceded with `f' are always unpacked, overwriting any more
-# recent file in the directory; those without are only
-# unpacked if there is no file present.
-starconf: make-starconf \
-		starconf.m4 \
-		bootstrap.installed
-	./make-starconf \
-		-f:starconf.m4 \
-		-xq:bootstrap:bootstrap.installed
+# True?
+# CLEANFILES=starconf
 
 # The edits of replacement variables (prefix and co) in
 # starlink.m4.in and starconf.in must be done at `make' time rather
@@ -41,23 +24,37 @@ starconf: make-starconf \
 # could legitimately be done at configure time -- it does not have to
 # be done this late -- but that would require us to have more than one
 # substitution step, which would be too confusing and messy.
-#
-# The set of !!...!!-substituted variables should be consistent with those in 
-# make-starconf.in
-edit = sed \
-	-e 's,@bindir\@,$(bindir),g' \
-	-e 's,@pkgdatadir\@,$(pkgdatadir),g' \
-	-e 's,@prefix\@,$(prefix),g' \
-	-e 's,@LN_S\@,$(LN_S),g' \
-	-e 's,@STARCONF_DEFAULT_STARLINK\@,@STARCONF_DEFAULT_STARLINK@,g' \
-	-e 's,@STARCONF_DEFAULT_PREFIX\@,@STARCONF_DEFAULT_PREFIX@,g' \
-	-e 's,@PACKAGE_VERSION\@,@PACKAGE_VERSION@,g' \
-	-e 's,@PACKAGE_VERSIONINT\@,@PACKAGE_VERSIONINT@,g'
-make-starconf: make-starconf.in configure.ac
-	rm -f make-starconf.tmp make-starconf
-	$(edit) $(srcdir)/make-starconf.in >make-starconf.tmp
-	mv make-starconf.tmp make-starconf
-	chmod +x make-starconf
+edit = @PERL@ -p \
+	-e 's,\@bindir\@,$(bindir),g;' \
+	-e 's,\@pkgdatadir\@,$(pkgdatadir),g;' \
+	-e 's,\@prefix\@,$(prefix),g;' \
+	-e 's,\@LN_S\@,$(LN_S),g;' \
+	-e 's,\@STARCONF_DEFAULT_STARLINK\@,@STARCONF_DEFAULT_STARLINK@,g;' \
+	-e 's,\@STARCONF_DEFAULT_PREFIX\@,@STARCONF_DEFAULT_PREFIX@,g;' \
+	-e 's,\@PACKAGE_VERSION\@,@PACKAGE_VERSION@,g;' \
+	-e 's,\@PACKAGE_VERSIONINT\@,@PACKAGE_VERSIONINT@,g;'
+starconf: starconf.in bootstrap.installed
+	rm -f starconf starconf.tmp
+	$(edit) \
+	    -e '/^##INCLUDE *(\S*)/ && do { open (F, "<$$1") || die "Unable to open $$1"; while(<F>) { print; } close (F); };' \
+	    $(srcdir)/starconf.in >starconf.tmp
+	mv starconf.tmp starconf
+	chmod +x starconf
+
+
+# The starconf.m4 file should be installed in the place where aclocal
+# expects to find macro files.
+install-data-local: starconf.m4
+	test -x $(bindir)/aclocal || { \
+	    echo "No $(bindir)/aclocal found" >&2; \
+	    false; \
+	}
+	inst=`$(bindir)/aclocal --print-ac-dir`; \
+	    test -n "$$inst" && \
+	    $(INSTALL_DATA) starconf.m4 $$inst && \
+	    if test -n "$$MANIFEST_FILE"; then \
+	        echo $$inst/starconf.m4 >>$$MANIFEST_FILE; \
+	    else :; fi
 
 # Magic: If there exists a bin directory at
 # @STARCONF_DEFAULT_PREFIX@/bin, then install links to the starconf
