Extend STAR_PATH_TCLTK to make the Tk test optional, and add an   optional test for itcl.  The itcl test doesn't actually do anything   at present, since I don't actually know what to test for.
svn path=/trunk/; revision=14346

diff --git a/buildsupport/starconf/starconf.m4.in b/buildsupport/starconf/starconf.m4.in
--- a/buildsupport/starconf/starconf.m4.in
+++ b/buildsupport/starconf/starconf.m4.in
@@ -467,19 +467,24 @@ AC_DEFUN([STAR_FC_LIBRARY_LDFLAGS],
 ])# STAR_FC_LIBRARY_LDFLAGS
 
 
-# STAR_PATH_TCLTK([minversion=0])
-# -------------------------------
+# STAR_PATH_TCLTK([minversion=0], [options=''])
+# ---------------------------------------------
 # Finds a tclsh and wish, and the associated libraries.  Sets output
 # variable TCL_CFLAGS to the C compiler flags necessary to compile
 # with Tcl, and TCL_LIBS to the required library flags.  Define
 # the cpp variable TCL_MISSING to 1 if Tcl is not available.  Similar
 # to macro AC_PATH_XTRA.
 #
-# If argument minversion is present, it specifies the minimum Tcl/Tk
+# If argument MINVERSION is present, it specifies the minimum Tcl/Tk
 # version number required.  The macro searches first in the path, and
 # then in a selection of platform-specific standard locations.  The
 # configure option --with-tcl allows you to provide a path to a tclsh
 # binary, which is put at the head of the list of locations to search.
+#
+# If the argument OPTIONS is present, it is a space-separated list of
+# the words 'tk' or 'itcl'.  If one or both of these is present, then
+# the macro will find a Tcl location which also has Tk or itcl
+# installed (note that the itcl test doesn't do anything at present).
 AC_DEFUN([STAR_PATH_TCLTK],
     [AC_ARG_WITH([tcl],
                  AS_HELP_STRING([--with-tcl],
@@ -487,9 +492,9 @@ AC_DEFUN([STAR_PATH_TCLTK],
                  [if test "X$withval" = Xno; then
                       _star_use_tcl=false
                   elif test "X$withval" = Xyes; then
-                      _star_use_tcl=true
+                      _star_use_tcl=:
                   else
-                      _star_use_tcl=true
+                      _star_use_tcl=:
                       _star_try_tcldir=$withval
                   fi])
      if $_star_use_tcl; then
@@ -499,6 +504,17 @@ AC_DEFUN([STAR_PATH_TCLTK],
              [star_cv_settcldir=unknown
               reqversint=`echo m4_ifval([$1], [$1], 0.0)-0-0 | [sed 's/\([0-9]*\)[^0-9]*\([0-9]*\)[^0-9]*\([0-9]*\).*/10000 \1* 100 \2*+ \3+p/']|dc`
               tclsources=`echo $PATH | sed "s/$PATH_SEPARATOR/ /g"`
+              if expr "x m4_ifval([$2], [$2], []) " : 'x.* tk ' >/dev/null; then
+                  search_tk=:
+              else
+                  search_tk=false
+              fi
+              if expr "x m4_ifval([$2], [$2], []) " : 'x.* itcl ' >/dev/null; then
+                  search_itcl=:
+              else
+                  search_itcl=false
+              fi
+              echo "tk=$search_tk  itcl=$search_itcl"
               stdsources='
 dnl  Search in /usr and /usr/local at least
 /usr/bin
@@ -507,27 +523,37 @@ dnl  /opt/local and /sw are the default installation locations for OpenDarwin
 dnl  and Fink on OSX
 /opt/local/bin
 /sw/bin'
-              for d in $_star_try_tcldir $tclsources $stdsources
+              for d in $_star_try_tcldir $STARCONF_DEFAULT_STARLINK/bin $tclsources $stdsources
               do
-                  if test -x $d/tclsh \
-                          -a -x $d/wish \
-                          -a -r $d/../include/tcl.h \
-                          -a -r $d/../include/tk.h; then
+                  echo "Trying in $d..."
+                  locok=:
+                  test -x $d/tclsh -a -r $d/../include/tcl.h || locok=false
+                  if $search_tk; then
+                      test -x $d/wish -a -r $d/../include/tk.h || locok=false
+                  fi
+                  if $search_itcl; then
+                      test -x $d/../lib/libitcl.aXXX || locok=false
+                  fi
+                  if $locok; then
                        if test ! -r $d/../lib/tclConfig.sh; then
-                           echo "$d/../lib/tclConfig.sh not found"
+                           echo "$d/../lib/tclConfig.sh unexpectedly missing"
                            break
                        fi
-                       if test ! -r $d/../lib/tkConfig.sh; then
-                           echo "$d/../lib/tkConfig.sh not found"
+                       if $search_tk && test ! -r $d/../lib/tkConfig.sh; then
+                           echo "$d/../lib/tkConfig.sh unexpectedly missing"
                            break
                        fi
                        rm -f conftest.sh
                        exec 8>conftest.sh
-                       echo tcldir=`cd $d/..; pwd` >&8
-                       echo reqversint=$reqversint >&8
+                       echo tcldir=`cd $d/..; pwd`   >&8
+                       echo search_tk=$search_tk     >&8
+                       echo search_itcl=$search_itcl >&8
+                       echo reqversint=$reqversint   >&8
                        cat <<\_STAREOF >&8
 . $tcldir/lib/tclConfig.sh
-. $tcldir/lib/tkConfig.sh
+if $search_tk; then
+    . $tcldir/lib/tkConfig.sh
+fi
 tclversint=`[echo $TCL_VERSION$TCL_PATCH_LEVEL-0-0 | sed 's/\([0-9]*\)[^0-9]*\([0-9]*\)[^0-9]*\([0-9]*\).*/10000 \1* 100 \2*+ \3+p/'|dc]`
 if test $tclversint -gt $reqversint; then
     # New enough version.
@@ -550,22 +576,34 @@ if test $tclversint -gt $reqversint; then
         tclsh_loc=
     fi
 
-    # Same for wish
-    lslink=`ls -l $tcldir/bin/wish`
-    wish_loc=`expr "x$lslink" : "x.*-> *\(.*\)"`
-    if test -n "$wish_loc" -a -x "$wish_loc"; then
-        : OK
-    elif test -x "$tcldir/bin/wish"; then
-        wish_loc="$tcldir/bin/wish"
-    else
-        echo "Warning: found Tk libraries, but not wish!" >&2
-        wish_loc=
+    temp_include="$TCL_INCLUDE_SPEC"
+    temp_libs="$TCL_LIB_SPEC"
+
+    if $search_tk; then
+        # Same for wish
+        lslink=`ls -l $tcldir/bin/wish`
+        wish_loc=`expr "x$lslink" : "x.*-> *\(.*\)"`
+        if test -n "$wish_loc" -a -x "$wish_loc"; then
+            : OK
+        elif test -x "$tcldir/bin/wish"; then
+            wish_loc="$tcldir/bin/wish"
+        else
+            echo "Warning: found Tk libraries, but not wish!" >&2
+            wish_loc=
+        fi
+        temp_libs="$temp_libs $TK_LIB_SPEC $TK_XLIBSW"
     fi
 
-    # These envs include $TCL_DBGX -- expand this out.
-    eval "I=\"$TCL_INCLUDE_SPEC\"; L=\"$TCL_LIB_SPEC $TK_LIB_SPEC $TK_XLIBSW\""
+    # similarly for $search_itcl
 
-    echo "TCL_CFLAGS=\"$I\"; TCL_LIBS=\"$L\"; TCLSH=\"$tclsh_loc\"; WISH=\"$wish_loc\""
+    # These envs include $TCL_DBGX -- expand this out.
+    eval "I=\"$temp_include\"; L=\"$temp_libs\""
+
+    res="TCL_CFLAGS=\"$I\"; TCL_LIBS=\"$L\"; TCLSH=\"$tclsh_loc\";"
+    if $search_tk; then
+        res="$res WISH=\"$wish_loc\";"
+    fi
+    echo $res
     status=0
 else
     echo "Found Tcl/Tk $TCL_VERSION$TCL_PATCH_LEVEL/$TK_VERSION$TK_PATCH_LEVEL: older than required" >&2
@@ -573,7 +611,7 @@ else
 fi
 exit $status
 _STAREOF
-                       exec 8<&-
+                       exec 8>&-
                        if /bin/sh conftest.sh >conftest.results; then
                            star_cv_settcldir=`cat conftest.results`
                        fi
