Added support for Firefox, just a copy of Mozilla setup. Will need testing.
svn path=/trunk/; revision=17519

diff --git a/applications/htx/browse b/applications/htx/browse
--- a/applications/htx/browse
+++ b/applications/htx/browse
@@ -119,6 +119,9 @@
 #        urlgen and showme scripts.
 #     9-SEP-2004 (BEC)
 #        Added support for OS X by opening URLs and HTML files with "open".
+#     7-Jun-2005 (SER)
+#        Added support for Firefox, just a copy of Mozilla setup. Will need
+#        testing.
 #     {enter_further_changes_here}
 
 #  Bugs:
@@ -381,6 +384,137 @@
             if test "${HTX_WHERE}" = 'i'; then settrap; fi
 
 #  Start a new invocation of Mozilla.
+#  -----------------------------------
+#  If the attempt to use an existing browser failed, then we must start a new
+#  one. Before doing so, check if the DISPLAY variable was set before invoking
+#  this script. If not, then issue a warning because running "xdisplay" each
+#  time will slow down document access.
+         else
+            if test ! "${wasset}" = '1'; then
+               echo >&2 \
+"${HTX_SCRIPT}: for faster access, please set DISPLAY to identify your X display"
+            fi
+
+#  Start a new browser, supplying the URL generated above. Suppress warning
+#  messages if required.
+            echo "Starting ${HTX_BROWSER} WWW browser..."
+            if test "${HTX_WARN}" = '1'; then
+               ${HTX_BROWSER} "${url}" &
+            else
+               ${HTX_BROWSER} 2>/dev/null "${url}" &
+            fi
+
+#  Disable the trap associated with temporary files, if necessary.
+            if test "${HTX_WHERE}" = 'i'; then settrap; fi
+         fi
+         ;;
+
+#
+#  Firefox.
+#  ========
+      *[Ff][Ii][Rr][Ee][Ff][Oo][Xx]*)
+
+#  Manage scratch file space.
+#  -------------------------
+#  If the document to be viewed is being supplied on standard input, then
+#  we must generate a name for a temporary file to store it.
+         if test "${HTX_WHERE}" = 'i'; then
+
+#  Use "ls" to list all the temporary file names so far used in reverse order
+#  of their creation time.
+            tempfiles="`ls -t ${tmpdir}/htx-browse-firefox-${LOGNAME}-*.html \
+                        2>/dev/null`"
+
+#  Pass this list of file names through "sed" to extract the sequence number
+#  field, quitting once that corresponding to the most recently created file
+#  has been obtained.
+            n="`echo "${tempfiles}" \
+            | sed -n 's%^.*/htx-browse-firefox-'"${LOGNAME}"'-\([1-9][0-9]*\)\.html$%\1%p
+                      t done
+                      b
+                      :done
+                      q'`"
+
+#  If no sequence number was found, then use 1. Otherwise increment it.
+            if test ! -n "${n}"; then n='1'; else n="`expr "${n}" + 1`"; fi
+
+#  Generate the temporary file name and replace the URL value with it. This
+#  name must be unique to the current machine, software, browser, user and
+#  temporary document sequence number.
+            url="${tmpdir}/htx-browse-firefox-${LOGNAME}-${n}.html"
+
+#  Select the names of all but the most recent few temporary files and remove
+#  these older ones if necessary.
+            oldfiles="`echo "${tempfiles}" | tail +3`"
+            if test -n "${oldfiles}"; then rm -f ${oldfiles}; fi
+         fi
+
+#  Ensure DISPLAY is set.
+#  ---------------------
+#  The DISPLAY variable is always required for firefox, so see if it is
+#  defined.
+         wasset='1'
+         if test ! -n "${DISPLAY}"; then
+            wasset=''
+
+#  If it was not defined, then search relative to directories ending in "/bin"
+#  that appear in $PATH to see if the Starlink "xdisplay" executable is
+#  available.
+            xdisplay="`IFS=':'; for dir in ${PATH}; do
+               case "${dir}" in */bin)
+                  file="${dir}/../etc/xdisplay"
+                  test -x "${file}" -a ! -d "${file}" && echo "${file}" \
+                                                      && break;;
+               esac
+            done`"
+
+#  If "xdisplay" was found, then use it to set a DISPLAY value. If possible,
+#  redirect standard input to the controlling terminal, since this affects
+#  results on some systems.
+            if test -n "${xdisplay}"; then
+               if test -n ${HTX_TTY}; then
+                  DISPLAY="`${xdisplay} <${HTX_TTY}`"
+               else
+                  DISPLAY="`${xdisplay}`"
+               fi
+
+#  If it could not be found, abort with an error message.
+            else
+               echo >&2 \
+               "${HTX_SCRIPT}: please set DISPLAY to identify your X display"
+               exit 1
+            fi
+         fi
+
+#  Prepare to communicate with Firefox.
+#  ------------------------------------
+#  Generate the Firefox remote command required to make an existing browser
+#  read the document.
+         if test "${HTX_WHERE}" = 'l' -o "${HTX_WHERE}" = 'i'; then
+            url=`echo "${url}" | sed 's#file://#file://localhost/#'`
+            remcmd="openURL(${url})"
+         else
+            remcmd="openURL(${url})"
+         fi
+
+#  If necessary, read the document from standard input into its temporary file.
+#  Before doing so, set a trap to remove the file if this script is aborted.
+         if test "${HTX_WHERE}" = 'i'; then
+            settrap 'rm -f "${url}"'
+            cat >"${url}" || exit
+         fi
+
+#  Try to use an existing invocation of Firefox.
+#  ----------------------------------------------
+#  Try to run Firefox with "-remote" to make an existing browser invocation
+#  read the document. Suppress any error messages.
+         if ${HTX_BROWSER} -noraise -remote "${remcmd}" > /dev/null 2>&1; then
+
+#  If successful, disable the trap associated with temporary files, if
+#  necessary.
+            if test "${HTX_WHERE}" = 'i'; then settrap; fi
+
+#  Start a new invocation of Firefox.
 #  -----------------------------------
 #  If the attempt to use an existing browser failed, then we must start a new
 #  one. Before doing so, check if the DISPLAY variable was set before invoking
