If we suppress the autoreconf, we must also suppress the check that it   worked (dummmm)
svn path=/trunk/; revision=12604

diff --git a/applications/bootstrap b/applications/bootstrap
--- a/applications/bootstrap
+++ b/applications/bootstrap
@@ -11,11 +11,11 @@ if $STAR_SUPPRESS_AUTORECONF; then
     echo "Suppressing autoreconf"
 else
     echorun autoreconf --install --symlink
-fi
 
-if test ! -x configure; then
-    echo "Ooooh dear, autoreconf didn't work -- I can't find ./configure"
-    exit 1
+    if test ! -x configure; then
+        echo "Ooooh dear, autoreconf didn't work -- I can't find ./configure"
+        exit 1
+    fi
 fi
 
 thisdir=`basename $PWD`
