Removed KAPPA dependencies. NETPBM tifftopnm for alpha.  Reworded & reordered description.  Added comments.
svn path=/trunk/; revision=1376

diff --git a/applications/convert/tiff2ndf.in b/applications/convert/tiff2ndf.in
--- a/applications/convert/tiff2ndf.in
+++ b/applications/convert/tiff2ndf.in
@@ -13,6 +13,15 @@
 #   Usage:
 #     tiff2ndf in [out]
 
+#  Description:
+#      This Bourne-shell script converts a 256 grey-level or
+#      black-and-white dithered Tag Image File Format (TIFF) into an
+#      unsigned-byte NDF file.  It handles one- or two-dimensional
+#      images.  The script uses various PBMPLUS utilities to produce a
+#      FITS file, flipped top to bottom, and then FITS2NDF to produce
+#      the final NDF.  Error messages are converted into Starlink style
+#      (preceded by !).
+ 
 #  Parameters:
 #     IN = FILENAME (Read)
 #        The name of the TIFF file to be converted (without the .tif 
@@ -21,15 +30,6 @@
 #        The name of the NDF to be generated (without the .sdf extension).
 #        If the OUT parameter is omitted, the value of the IN parameter
 #        is used.
- 
-#  Description:
-#      This Bourne shell script converts a 256 grey-level or
-#      black-and-white dithered Tag Image File Format (TIFF) into a
-#      Starlink NDF file.  One or two-dimensional images can be handled.
-#      The script uses various PBMPLUS utilities to produce a FITS file 
-#      and then KAPPA applications FITSDIN, MATHS and FLIP to produce
-#      the final NDF.  Error messages are converted into Starlink style
-#      (preceded by !).
  
 #  Examples:
 #     tiff2ndf old new
@@ -42,8 +42,8 @@
 #  Notes:
 #     -  This initial version of the script handles only greyscale
 #     or b/w dithered images.  You are responsible for conversion of
-#     your images to this format prior to use.  This ensures that the
-#     user is responsible for converting RGB values to brightness values.
+#     your images to this format prior to use, including the
+#     conversion of RGB values to brightness values.
 #
 #     -  Input image file names must have the extension .tif.
 #
@@ -67,16 +67,13 @@
 #     1995 November 13 (AJC):
 #        Added fileout parameter, and error reporting and exit at each
 #        stage.  Use long temporary filenames.
+#     1997 August 1 (MJC):
+#        Removed KAPPA dependencies.  Reworded and reordered the
+#        description.  Added some comments.  Used a special tifftopnm
+#        for alpha_OSF1.
  
 #  Bugs:
-#     At the time of writing, this utility does not work on alpha OSF/1
-#     due to a problem with tifftopnm in the standard release of 
-#     PBMPLUS.  OSF/1 users should use a copy of tifftopnm obtained from 
-#     Netpbm which is based on PBMPLUS but contains many improvements and
-#     additions.  A suitable version may be obtained via WWW at
-#     http://www.astro.cf.ac.uk/pub/Grant.Privett/.  Alternatively,
-#     contact Grant Privett, gjp@astronomy.cardiff.ac.uk.
-#     {note_further_bugs_here}
+#     {note_any_bugs_here}
  
 #-
 
@@ -84,60 +81,52 @@
 out=${2:-$1}
 name=`basename $1`
 
+# Determine whether the operating system is alpha_OSF1 or not.
+machine=`uname -m`
+opsys=`uname`
+
 # Convert the image removing temporary files at each stage.
 
-# Convert image from TIFF format to FITS.
-tifftopnm $1.tif 2> convert_err1_$name.lis | \
-ppmtopgm 2> convert_err2_$name.lis | \
-pgmtofits 2> convert_err3_$name.lis > convert_temp_$name.fit || \
-  { sed 's/^/!  TIFF2NDF:/' convert_err?_$name.lis 1>&2
-    rm -f convert_err?_$name.lis convert_temp_$name.fit
-    exit 1
-  }
-  rm -f convert_err?_$name.lis
- 
-# Convert image to an NDF. 
-$KAPPA_DIR/fitsdin files=convert_temp_$name.fit out=convert_temp_$name fmtcnv \
+# Convert image from TIFF format to FITS, flipping it from top to bottom.
+# Use the Netpbm version of tifftopnm on alpha_OSF1 because of a bug
+# in the released PBMPLUS version.  The error output is written to
+# temporary files.  Make the error look as if it came from MSG.
+if test "$machine" = "alpha" -a  "$opsys" = "OSF1"
+then
+   $CONVERT_DIR/tifftopnm $1.tif 2> convert_err1_$name.lis | \
+   ppmtopgm 2> convert_err2_$name.lis | \
+   pnmflip -topbottom 2> convert_err3_$name.lis | \
+   pgmtofits 2> convert_err4_$name.lis > convert_temp_$name.fit || \
+     { sed 's/^/!  TIFF2NDF:/' convert_err?_$name.lis 1>&2
+       rm -f convert_err?_$name.lis convert_temp_$name.fit
+       exit 1
+     }
+
+else
+   tifftopnm $1.tif 2> convert_err1_$name.lis | \
+   ppmtopgm 2> convert_err2_$name.lis | \
+   pnmflip -topbottom 2> convert_err3_$name.lis | \
+   pgmtofits 2> convert_err4_$name.lis > convert_temp_$name.fit || \
+     { sed 's/^/!  TIFF2NDF:/' convert_err?_$name.lis 1>&2
+       rm -f convert_err?_$name.lis convert_temp_$name.fit
+       exit 1
+     }
+fi
+rm -f convert_err?_$name.lis
+
+# Convert the image to an NDF of data type _UBYTE.  Make the error look
+# as if it came from MSG, so as this is a secondary error report, 
+# replace the !! prefix with !.
+$CONVERT_DIR/fits2ndf in=convert_temp_$name.fit out=$out fmtcnv=t \
   </dev/null  2>&1 | \
   sed 's/^\!\!/\! /' | \
   awk \
 'BEGIN{err=0}\
-/^\!/{if(err==0){err=1;print "!! TIFF2NDF: Error reports from KAPPA:FITSDIN"}};\
+/^\!/{if(err==0){err=1;print "!! GIF2NDF: Error reports from FITS2NDF"}};\
 {print}\
 END{if(err==1){exit 1}}' || \
   (rm -f convert_temp_$name.fit
-   echo "!  TIFF2NDF: Abandoned at FITSDIN"
+   echo "!  TIFF2NDF: Abandoned at FITS2NDF"
    exit 1
   ) || exit 1
   rm -f convert_temp_$name.fit
- 
-# Convert image values to 8 bits.
-$KAPPA_DIR/maths exp="ia+max(0,-sign(255,IA))" ia=convert_temp_$name \
-  out=convert_temp_u$name \
-  </dev/null  2>&1 | \
-  sed 's/^\!\!/\! /' | \
-  awk \
-'BEGIN{err=0}\
-/^\!/{if(err==0){err=1;print "!! TIFF2NDF: Error reports from KAPPA:MATHS"}};\
-{print}\
-END{if(err==1){exit 1}}' || \
-  (rm -f convert_temp_$name.sdf
-   echo "!  TIFF2NDF: Abandoned at MATHS"
-   exit 1
-  ) || exit 1
-  rm -f convert_temp_$name.sdf 
- 
-# Invert the image.
-$KAPPA_DIR/flip in=convert_temp_u$name out=$out dim=2
-  </dev/null  2>&1 | \
-  sed 's/^\!\!/\! /' | \
-  awk \
-'BEGIN{err=0}\
-/^\!/{if(err==0){err=1;print "!! TIFF2NDF: Error reports from KAPPA:FLIP"}};\
-{print}\
-END{if(err==1){exit 1}}' || \
-  (rm -f convert_temp_u$name.sdf
-   echo "!  TIFF2NDF: Abandoned at FLIP"
-   exit 1
-  ) || exit 1
-  rm -f convert_temp_u$name.sdf 
