Fix autoconf quoting goof.
svn path=/trunk/; revision=15526

diff --git a/applications/gaia/tcl/itcl/itcl/unix/configure b/applications/gaia/tcl/itcl/itcl/unix/configure
--- a/applications/gaia/tcl/itcl/itcl/unix/configure
+++ b/applications/gaia/tcl/itcl/itcl/unix/configure
@@ -2866,9 +2866,9 @@ else
 fi;
 if test "$ok" = "yes"; then
     if test ${TCL_SHARED_BUILD} = 0; then
-        { { echo "$as_me:$LINENO: error: Tcl was not built with --enable-shared" >&5
-echo "$as_me: error: Tcl was not built with --enable-shared" >&2;}
-   { (exit so you can't use shared libraries.); exit so you can't use shared libraries.; }; }
+        { { echo "$as_me:$LINENO: error: Tcl was not built with --enable-shared, so you can't use shared libraries." >&5
+echo "$as_me: error: Tcl was not built with --enable-shared, so you can't use shared libraries." >&2;}
+   { (exit 1); exit 1; }; }
     fi
     SHLIB_CFLAGS="${SHLIB_CFLAGS}"
     eval "ITCL_LIB_FILE=libitcl${VERSION}${SHLIB_SUFFIX}"
