Added a test of whether the SGML source file is actually present: quick sanity-check suggested by Mark.
svn path=/trunk/; revision=6599

diff --git a/applications/sgmlkit/bin/sgml2docs b/applications/sgmlkit/bin/sgml2docs
--- a/applications/sgmlkit/bin/sgml2docs
+++ b/applications/sgmlkit/bin/sgml2docs
@@ -202,6 +202,12 @@ case $SGMLSRC in
 	*) SGMLSRC=$PWD/$SGMLSRC ;;
 esac
 
+# Sanity-check: we _do_ have a source file, don't we?
+if [ ! -r $SGMLSRC ]; then
+    echo "$PROGNAME:E: I can't find file $SGMLSRC !"
+    exit 1
+fi
+
 $VERBOSE && echo "$PROGNAME:I: Processing $SGMLSRC..."
 case $TARGETFORMAT in
     0)  $VERBOSE && echo "$PROGNAME:I: Target HTML...";
