Significant changes to the way maths is processed, so that the generated <img> elements now have height and width attributes.
- img-eqlist.dtd modified so that the img-eq element now has optional
  width and height attributes.  Also made it into an XML DTD -- why
  not?
- img-eqlist.pl modified so that, rather than generating
  $ROOT.imgeq.sgml, it generates $ROOT.imgeq.labelmap, with lines
  consisting of a label and an image filename.
- In sgml2docs, dvi2bitmap is called with the -Qb option (requires
  dvi2bitmap, v0.8-1), and the output from that is saved.  This output
  consists of a series of lines with an image filename, plus width and
  height.  This output, plus the img-eqlist labelmap are fed to an awk
  script which generates the $ROOT.imgeq.xml file, complete with
  width/height attributes.
- slmaths.dsl reads this img-eqlist XML file, and generates <img>
  elements with the correct filenames and sizes.

svn path=/trunk/; revision=6548

diff --git a/applications/sgmlkit/bin/sgml2docs b/applications/sgmlkit/bin/sgml2docs
--- a/applications/sgmlkit/bin/sgml2docs
+++ b/applications/sgmlkit/bin/sgml2docs
@@ -296,7 +296,7 @@ if [ $TARGETFORMAT -eq 0 ]; then
     if [ -s "$ROOT.imgeq.list" ]; then
 	# Find dvi2bitmap's default format
 	# Default to gif if the dvi2bitmap version doesn't have the -Qt option
-	#imgfmt=`($DVI2BITMAP -Qt 2>/dev/null || echo gif) | awk '{print $1}'`
+	#imgfmt=`($DVI2BITMAP -Qt 2>/dev/null || echo gif gif) | awk '{print $2}'`
 	# Force the image format to be gif -- PNG transparency isn't
 	# yet well-enough supported in browsers.
 	imgfmt='gif'
@@ -306,8 +306,14 @@ if [ $TARGETFORMAT -eq 0 ]; then
 	$VERBOSE && echo "$PROGNAME:I: $LATEX $ROOT.imgeq.tex"
 	$run $LATEX $ROOT.imgeq.tex $OUTPUTDEST
 
-	$VERBOSE && echo "$PROGNAME:I: $DVI2BITMAP -m 2 -s 2 -Pt $ROOT.imgeq.dvi"
-	$run $DVI2BITMAP -m 2 -s 2 -Pt $ROOT.imgeq.dvi $OUTPUTDEST
+	$VERBOSE && echo "$PROGNAME:I: $DVI2BITMAP -m 2 -s 2 -Pt $ROOT.imgeq.dvi" 
+	$run $DVI2BITMAP -m 2 -s 2 -Pt -q -Qb $ROOT.imgeq.dvi >dvi2bitmap.log
+
+	if [ -r dvi2bitmap.log -a -r $ROOT.imgeq.labelmap ]; then
+	    awk '/^Qb/ { map[$2]=sprintf(" width=\"%s\" height=\"%s\"",$3,$4); };/^label/ { printf("<img-eq label=\"%s\" sysid=\"%s\"%s/>\n",$2,$3,map[$3]?map[$3]:"");};BEGIN { print "<?xml version=\"1.0\"?>\n<!DOCTYPE img-eqlist SYSTEM \"img-eqlist\">\n<img-eqlist>";};END {print "</img-eqlist>"; }' dvi2bitmap.log $ROOT.imgeq.labelmap >$ROOT.imgeq.xml
+	else
+	    echo "$PROGNAME:W: failed generating equation-image refs"
+	fi
     else
 	$VERBOSE && echo "$PROGNAME:I: no maths in document"
     fi
