New starconf bootstrap file created in libraries/pcs, and the   bootstrap files removed from pcs/*, since there are no longer   components.
svn path=/trunk/; revision=15981

diff --git a/libraries/pcs/bootstrap b/libraries/pcs/bootstrap
--- a/libraries/pcs/bootstrap
+++ b/libraries/pcs/bootstrap
@@ -1,48 +1,133 @@
 #! /bin/sh -
-# This is not a starconf component bootstrap file; it should be maintained
-# as a copy of buildsupport/starconf/bootstrap.bridging:
-#   $Source: /cvs/buildsupport/starconf/bootstrap.bridging,v $
-#   $Revision: 1.1 $
-# (check this in to CVS using -ko to preserve above RCS info).
+# original bootstrap file, installed by starconf 1.2, rnum=1002000
+# If you _need_ to change this file, delete `original' in the line above,
+# or else starconf may overwrite it with an updated version.
 #
-# Instead, it is a bootstrap script used for `bridging' directories,
-# such as applications/ and libraries/, which group together related
-# components and, when they are bootstrapped, bridge between the parent
-# and the various children listed in the AC_CONFIG_SUBDIRS macro in the
-# configure.ac in this directory.  That is, it is for directories which
-# are traversed by the top-level bootstrap, but which are not components.
+# bootstrap.installed.  Generated from bootstrap.installed.in by configure.
+#
+# Bootstrap a checked-out component of the Starlink software tree.
+# Run this script in a freshly checked-out directory to bring the
+# system to the point where you can just type ./configure;make
+#
+# Usage:
+#     ./bootstrap
 
 
-# If STAR_SUPPRESS_AUTORECONF is true in the environment, then we
-# suppress the call of `autoreconf', and simply invoke ./bootstrap in
-# the children.  This is here _only_ so that the top-level bootstrap
-# file can suppress multiple calls of this in bootstrap scripts in its
-# children, and as an optimisation.  As such, it makes sense ONLY when
-# invoked from a top-level bootstrap.  This mechanism must not be used
-# by users, as it is liable to change without warning.
-: ${STAR_SUPPRESS_AUTORECONF=false}
+# This script should be installed, by starconf, in all `component
+# directories'.  A `component directory' is a directory which has a
+# component.xml.in file in it.  All component directories will have a
+# manifest file created and installed in .../manifests; non-component
+# directories will not have manifest files.  Everything that's
+# installed should be installed as part of some component
+# or other.
+#
+# The ./bootstrap scripts will stop recursing when they find a
+# component.xml.in file.  They'll warn if they find a component.xml.in
+# file in any AC_CONFIG_SUBDIRS directory, but ignore it, and exit
+# with an error if they do not find a component.xml.in file and there
+# are no AC_CONFIG_SUBDIRS directories in which to search further.
+# That is, the tree of directories which the top-level bootstrap
+# traverses should have component.xml.in files at or above all its
+# leaves.
 
-if $STAR_SUPPRESS_AUTORECONF; then
-    echo "Suppressing autoreconf"
 
-    thisdir=`basename $PWD`
-    for d in `autoconf --trace=AC_CONFIG_SUBDIRS:$% configure.ac` DUMMY
-    do
-        if test -n "$d" -a -d "$d"; then
-            echo "Bootstrapping $thisdir/$d..."
-            (cd $d && ./bootstrap)
+# The starconf below might update bootstrap, if a newer version is
+# available.  Unfortunately, this confuses sh, which appears _not_ to
+# keep open the script it's reading, but to reopen it afresh, or reseek
+# within the file, for each line (or something like that!?).
+# So rewrite this script to a temporary file and exec it.
+tempfile="${TMP-/tmp}/$0-$$.tmp"
+rm -f $tempfile
+echo "trap 'rm -f $tempfile' 0" >$tempfile   # remove temporary at exit
+sed '1,/^--TRAMPOLINE--/d' $0 >>$tempfile    # strip out the trampoline
+exec /bin/sh $tempfile                       # exec the temporary
+--TRAMPOLINE--
+
+
+echo "Bootstrapping `pwd` ..."
+
+if test ! -f configure.ac; then
+    echo "bootstrap: No configure.ac in directory `pwd`" >&2
+    exit 1
+fi
+
+subdirs=`autoconf --trace=AC_CONFIG_SUBDIRS:$% configure.ac`
+
+if test -f component.xml.in; then
+
+    if starconf --show buildsupport >/dev/null 2>&1; then
+
+        # starconf is in the path
+        echo "...using starconf in " `starconf --show buildsupport`
+        starconf || exit 1
+
+    else
+
+        # The temptation here is to use ./starconf.status to find the
+        # starconf that it came from and invoke that explicitly.  Don't do
+        # this, however: we don't want to be too clever, and it's better
+        # to be consistent with the way the autotools behave (the first
+        # one in your path is the one that works, and they don't have this
+        # sort of `phone home' cleverness in them).
+
+        echo "bootstrap error: The starconf application is not in your path"
+
+        # This doesn't stop us being helpful, however.
+        if test -f ./starconf.status; then
+            starconf_home=`./starconf.status --show buildsupport`
+            echo "This directory was last bootstrapped with $starconf_home/bin/starconf"
         fi
-    done
+
+        exit 1
+    fi
+
+    # Check that there are no component.xml.in files in any subdirectories
+    if test -n "$subdirs"; then
+        for d in $subdirs
+        do
+            if test -d "$d" && test -f "$d/component.xml.in"; then
+                echo "bootstrap: warning: ignoring child $d/component.xml.in" >&2
+            fi
+        done
+    fi
+
+    # If STAR_SUPPRESS_AUTORECONF is true in the environment, then we
+    # suppress the call of `autoreconf'.  This is here _only_ so that
+    # the top-level bootstrap file can suppress multiple calls of this
+    # in bootstrap scripts in its children.  This mechanism must not
+    # be used by users, as it is likely to change without warning. 
+    if ${STAR_SUPPRESS_AUTORECONF-false}; then
+        echo "Suppressing autoreconf in" `pwd`
+    else
+        echo autoreconf --install --symlink
+        autoreconf --install --symlink || exit 1
+    fi
 
 else
 
-    echo "autoreconf --install --symlink" || exit 1
-    autoreconf --install --symlink
+    # This is not a component directory, so simply recurse into the children.
 
-    if test ! -f configure; then
-        echo "Ooooh dear, autoreconf didn't work -- I can't find ./configure"
+    # ...if there are any, that is.
+    if test -z "$subdirs"; then
+        echo "bootstrap: error: non-component directory `pwd` has no subdirs" >&2
         exit 1
     fi
+
+    # Bootstrap the child directories mentioned in AC_CONFIG_SUBDIRS.
+    # These bootstrap files must exist.
+    for d in $subdirs
+    do
+        if test -d "$d"; then
+            echo "Bootstrapping $d..."
+            if test -f $d/bootstrap; then
+                # good...
+                (cd $d; /bin/sh ./bootstrap)
+            else
+                echo "bootstrap: no file $d/bootstrap" >&2
+                exit 1
+            fi
+        fi
+    done
 
 fi
 
