Silly, that arrangement removed all the source files (csources etc. are used in a preceeding Tcl macro), so the compiler checks and package checks are now split into two macros.
svn path=/trunk/; revision=24374

diff --git a/applications/gaia/gaia/configure b/applications/gaia/gaia/configure
--- a/applications/gaia/gaia/configure
+++ b/applications/gaia/gaia/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 #endif"
 
 ac_default_prefix=/export/pwda/pdraper/starlink_cvs/build
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS PKG_SOURCES PKG_OBJECTS CLEANFILES TCL_INCLUDES TK_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS SHLIB_SUFFIX DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LD_LIBS LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LD_LIBRARY_PATH_VAR TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB TCLSH_PROG WISH_PROG OS tclutil_VERSION tclutil_LIB_FILE tclutil_BUILD_LIB_SPEC tclutil_BUILD_DIR tclutil_LIB_SPEC BLT_LIB_SPEC BLT_LIB_DIR tclutil_SRC_DIR tclutil_PKG_OBJECTS astrotcl_VERSION astrotcl_LIB_FILE astrotcl_BUILD_LIB_SPEC astrotcl_BUILD_DIR astrotcl_LIB_SPEC astrotcl_SRC_DIR astrotcl_PKG_OBJECTS rtd_VERSION rtd_LIB_FILE rtd_BUILD_LIB_SPEC rtd_BUILD_DIR rtd_LIB_SPEC rtd_SRC_DIR rtd_PKG_OBJECTS cat_VERSION cat_LIB_FILE cat_BUILD_LIB_SPEC cat_BUILD_DIR cat_LIB_SPEC cat_SRC_DIR skycat_VERSION skycat_LIB_FILE skycat_BUILD_LIB_SPEC skycat_BUILD_DIR skycat_LIB_SPEC skycat_SRC_DIR SHLIB_LD_CXX_LIBS STARLINK STAR_CPPFLAGS STAR_FCFLAGS STAR_FFLAGS STAR_LDFLAGS build build_cpu build_vendor build_os FC FCFLAGS ac_ct_FC C_FC_FCLINK_MAGIC C_FC_PPFC_FCLINK_MAGIC stardocsdir staretcdir starexamplesdir starfacsdir starhelpdir starnewsdir STAR_DEPENDENCIES_ATTRIBUTES STAR_DEPENDENCIES_CHILDREN STAR_DOCUMENTATION PACKAGE_VERSION_MAJOR PACKAGE_VERSION_MINOR PACKAGE_VERSION_RELEASE PACKAGE_VERSION_INTEGER STAR_MANIFEST_DIR PREDIST PAX TAR LIBTOOL FGENERIC FCLIBS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CYGPATH EXEEXT PKG_LIB_FILE PKG_STUB_LIB_FILE PKG_STUB_SOURCES PKG_STUB_OBJECTS PKG_TCL_SOURCES PKG_HEADERS PKG_INCLUDES PKG_LIBS PKG_CFLAGS TCL_VERSION TCL_BIN_DIR TCL_SRC_DIR TCL_LIB_FILE TCL_LIB_FLAG TCL_LIB_SPEC TCL_STUB_LIB_FILE TCL_STUB_LIB_FLAG TCL_STUB_LIB_SPEC TCL_LIBS TCL_DEFS TCL_EXTRA_CFLAGS TCL_LD_FLAGS TCL_SHLIB_LD_LIBS TK_VERSION TK_BIN_DIR TK_SRC_DIR TK_LIB_FILE TK_LIB_FLAG TK_LIB_SPEC TK_STUB_LIB_FILE TK_STUB_LIB_FLAG TK_STUB_LIB_SPEC TK_LIBS TK_XINCLUDES CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC OBJEXT CPP CXX CXXFLAGS ac_ct_CXX INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA SET_MAKE RANLIB ac_ct_RANLIB EGREP MATH_LIBS tclutil_VERSION tclutil_LIB_FILE tclutil_BUILD_LIB_SPEC tclutil_BUILD_DIR tclutil_LIB_SPEC BLT_LIB_SPEC BLT_LIB_DIR tclutil_SRC_DIR tclutil_PKG_OBJECTS astrotcl_VERSION astrotcl_LIB_FILE astrotcl_BUILD_LIB_SPEC astrotcl_BUILD_DIR astrotcl_LIB_SPEC astrotcl_SRC_DIR astrotcl_PKG_OBJECTS rtd_VERSION rtd_LIB_FILE rtd_BUILD_LIB_SPEC rtd_BUILD_DIR rtd_LIB_SPEC rtd_SRC_DIR rtd_PKG_OBJECTS cat_VERSION cat_LIB_FILE cat_BUILD_LIB_SPEC cat_BUILD_DIR cat_LIB_SPEC cat_SRC_DIR skycat_VERSION skycat_LIB_FILE skycat_BUILD_LIB_SPEC skycat_BUILD_DIR skycat_LIB_SPEC skycat_SRC_DIR PKG_SOURCES PKG_OBJECTS CLEANFILES TCL_INCLUDES TK_INCLUDES TCL_THREADS SHARED_BUILD AR CELIB_DIR LIBOBJS SHLIB_SUFFIX DL_LIBS CFLAGS_DEBUG CFLAGS_OPTIMIZE CFLAGS_WARNING STLIB_LD SHLIB_LD SHLIB_CFLAGS SHLIB_LD_LIBS LDFLAGS_DEBUG LDFLAGS_OPTIMIZE LD_LIBRARY_PATH_VAR TCL_DBGX CFLAGS_DEFAULT LDFLAGS_DEFAULT MAKE_LIB MAKE_SHARED_LIB MAKE_STATIC_LIB MAKE_STUB_LIB RANLIB_STUB TCLSH_PROG WISH_PROG OS SHLIB_LD_CXX_LIBS STARLINK STAR_CPPFLAGS STAR_FCFLAGS STAR_FFLAGS STAR_LDFLAGS build build_cpu build_vendor build_os FC FCFLAGS ac_ct_FC C_FC_FCLINK_MAGIC C_FC_PPFC_FCLINK_MAGIC stardocsdir staretcdir starexamplesdir starfacsdir starhelpdir starnewsdir STAR_DEPENDENCIES_ATTRIBUTES STAR_DEPENDENCIES_CHILDREN STAR_DOCUMENTATION PACKAGE_VERSION_MAJOR PACKAGE_VERSION_MINOR PACKAGE_VERSION_RELEASE PACKAGE_VERSION_INTEGER STAR_MANIFEST_DIR PREDIST PAX TAR LIBTOOL FGENERIC FCLIBS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -6690,6 +6690,109 @@ done
     fi
 
 
+#--------------------------------------------------------------------
+# Do application specific checks (see aclocal.m4)
+#--------------------------------------------------------------------
+
+
+# Load the Tclutil definitions
+cf=${prefix}/lib/tclutilConfig.sh
+if test -f $cf ; then
+    . $cf
+
+
+
+
+
+
+
+
+
+else
+    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
+echo "$as_me: error: $cf doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# Load the Astrotcl definitions
+cf=${prefix}/lib/astrotclConfig.sh
+if test -f $cf ; then
+    . $cf
+
+
+
+
+
+
+
+else
+    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
+echo "$as_me: error: $cf doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# Load the Rtd definitions
+cf=${prefix}/lib/rtdConfig.sh
+if test -f $cf ; then
+    . $cf
+
+
+
+
+
+
+
+else
+    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
+echo "$as_me: error: $cf doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# Load the Cat definitions
+cf=${prefix}/lib/catConfig.sh
+if test -f $cf ; then
+    . $cf
+
+
+
+
+
+
+
+else
+    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
+echo "$as_me: error: $cf doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# Load the SkyCat definitions
+cf=${prefix}/lib/skycatConfig.sh
+if test -f $cf ; then
+    . $cf
+
+
+
+
+
+
+else
+    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
+echo "$as_me: error: $cf doesn't exist" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+csources=`cd ${srcdir}; echo generic/*.[Cc] tkhtml/*.c`
+fsources=`cd ${srcdir}; echo generic/*.f`
+gsources=`cd ${srcdir}; echo generic/*.gen generic/*.gsc generic/*.gsn`
+
+
+gaia_headers=`cd ${srcdir}; echo generic/*.h generic/*.icc`
+gaia_includes="-I. -I${srcdir}/generic -I${srcdir}/bitmaps -I${prefix}/include/skycat -I${prefix}/include/rtd -I${prefix}/include/cat -I${prefix}/include/astrotcl -I${prefix}/include/tclutil"
+tclsources=`cd ${srcdir}; echo library/*.tcl library/*.itk library/*.xpm library/skycat2.0.cfg`
+
+
+
 #-----------------------------------------------------------------------
 # __CHANGE__
 # Specify the C source files to compile in TEA_ADD_SOURCES,
@@ -11158,13 +11261,7 @@ OS=`uname`
 
 
 #--------------------------------------------------------------------
-# Prefer to include a config.h file.
-#--------------------------------------------------------------------
-          ac_config_headers="$ac_config_headers config.h"
-
-
-#--------------------------------------------------------------------
-# Do application specific checks (see aclocal.m4)
+# Local tests that depend on the compiler setup, including CFLAGS
 #--------------------------------------------------------------------
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
@@ -11290,7 +11387,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:11293:" \
+echo "$as_me:11390:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -11541,7 +11638,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:11544: \"$ac_link\") >&5
+(eval echo $as_me:11641: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -11619,7 +11716,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:11622: \"$ac_link\") >&5
+(eval echo $as_me:11719: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -11792,102 +11889,6 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-
-# Load the Tclutil definitions
-cf=${prefix}/lib/tclutilConfig.sh
-if test -f $cf ; then
-    . $cf
-
-
-
-
-
-
-
-
-
-else
-    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
-echo "$as_me: error: $cf doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-# Load the Astrotcl definitions
-cf=${prefix}/lib/astrotclConfig.sh
-if test -f $cf ; then
-    . $cf
-
-
-
-
-
-
-
-else
-    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
-echo "$as_me: error: $cf doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-# Load the Rtd definitions
-cf=${prefix}/lib/rtdConfig.sh
-if test -f $cf ; then
-    . $cf
-
-
-
-
-
-
-
-else
-    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
-echo "$as_me: error: $cf doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-# Load the Cat definitions
-cf=${prefix}/lib/catConfig.sh
-if test -f $cf ; then
-    . $cf
-
-
-
-
-
-
-
-else
-    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
-echo "$as_me: error: $cf doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-# Load the SkyCat definitions
-cf=${prefix}/lib/skycatConfig.sh
-if test -f $cf ; then
-    . $cf
-
-
-
-
-
-
-else
-    { { echo "$as_me:$LINENO: error: $cf doesn't exist" >&5
-echo "$as_me: error: $cf doesn't exist" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-csources=`cd ${srcdir}; echo generic/*.[Cc] tkhtml/*.c`
-fsources=`cd ${srcdir}; echo generic/*.f`
-gsources=`cd ${srcdir}; echo generic/*.gen generic/*.gsc generic/*.gsn`
-
-
-gaia_headers=`cd ${srcdir}; echo generic/*.h generic/*.icc`
-gaia_includes="-I. -I${srcdir}/generic -I${srcdir}/bitmaps -I${prefix}/include/skycat -I${prefix}/include/rtd -I${prefix}/include/cat -I${prefix}/include/astrotcl -I${prefix}/include/tclutil"
-tclsources=`cd ${srcdir}; echo library/*.tcl library/*.itk library/*.xpm library/skycat2.0.cfg`
 
 # -----------------------------------------------------------------------
 # 	Check if we need (or can use) the socklen_t type.
@@ -12875,7 +12876,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:12878:" \
+echo "$as_me:12879:" \
      "checking for Fortran compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -13450,7 +13451,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_verb"
-(eval echo $as_me:13453: \"$ac_link\") >&5
+(eval echo $as_me:13454: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -13528,7 +13529,7 @@ _ACEOF
 # flags.
 ac_save_FFLAGS=$FCFLAGS
 FCFLAGS="$FCFLAGS $ac_cv_prog_fc_v"
-(eval echo $as_me:13531: \"$ac_link\") >&5
+(eval echo $as_me:13532: \"$ac_link\") >&5
 ac_fc_v_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_fc_v_output" >&5
 FCFLAGS=$ac_save_FFLAGS
@@ -14270,6 +14271,12 @@ PKG_LIBS="${PKG_LIBS} ${STAR_LDFLAGS} `atl_link` `ard_link -myerr -mygrf` \
 
 
 #--------------------------------------------------------------------
+# Prefer to include a config.h file.
+#--------------------------------------------------------------------
+          ac_config_headers="$ac_config_headers config.h"
+
+
+#--------------------------------------------------------------------
 # Finally, substitute all of the various values into the Makefile.
 # You may alternatively have a special pkgIndex.tcl.in or other files
 # which require substituting th AC variables in.  Include these here.
@@ -14941,39 +14948,6 @@ s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@EGREP@,$EGREP,;t t
 s,@MATH_LIBS@,$MATH_LIBS,;t t
-s,@PKG_SOURCES@,$PKG_SOURCES,;t t
-s,@PKG_OBJECTS@,$PKG_OBJECTS,;t t
-s,@CLEANFILES@,$CLEANFILES,;t t
-s,@TCL_INCLUDES@,$TCL_INCLUDES,;t t
-s,@TK_INCLUDES@,$TK_INCLUDES,;t t
-s,@TCL_THREADS@,$TCL_THREADS,;t t
-s,@SHARED_BUILD@,$SHARED_BUILD,;t t
-s,@AR@,$AR,;t t
-s,@CELIB_DIR@,$CELIB_DIR,;t t
-s,@LIBOBJS@,$LIBOBJS,;t t
-s,@SHLIB_SUFFIX@,$SHLIB_SUFFIX,;t t
-s,@DL_LIBS@,$DL_LIBS,;t t
-s,@CFLAGS_DEBUG@,$CFLAGS_DEBUG,;t t
-s,@CFLAGS_OPTIMIZE@,$CFLAGS_OPTIMIZE,;t t
-s,@CFLAGS_WARNING@,$CFLAGS_WARNING,;t t
-s,@STLIB_LD@,$STLIB_LD,;t t
-s,@SHLIB_LD@,$SHLIB_LD,;t t
-s,@SHLIB_CFLAGS@,$SHLIB_CFLAGS,;t t
-s,@SHLIB_LD_LIBS@,$SHLIB_LD_LIBS,;t t
-s,@LDFLAGS_DEBUG@,$LDFLAGS_DEBUG,;t t
-s,@LDFLAGS_OPTIMIZE@,$LDFLAGS_OPTIMIZE,;t t
-s,@LD_LIBRARY_PATH_VAR@,$LD_LIBRARY_PATH_VAR,;t t
-s,@TCL_DBGX@,$TCL_DBGX,;t t
-s,@CFLAGS_DEFAULT@,$CFLAGS_DEFAULT,;t t
-s,@LDFLAGS_DEFAULT@,$LDFLAGS_DEFAULT,;t t
-s,@MAKE_LIB@,$MAKE_LIB,;t t
-s,@MAKE_SHARED_LIB@,$MAKE_SHARED_LIB,;t t
-s,@MAKE_STATIC_LIB@,$MAKE_STATIC_LIB,;t t
-s,@MAKE_STUB_LIB@,$MAKE_STUB_LIB,;t t
-s,@RANLIB_STUB@,$RANLIB_STUB,;t t
-s,@TCLSH_PROG@,$TCLSH_PROG,;t t
-s,@WISH_PROG@,$WISH_PROG,;t t
-s,@OS@,$OS,;t t
 s,@tclutil_VERSION@,$tclutil_VERSION,;t t
 s,@tclutil_LIB_FILE@,$tclutil_LIB_FILE,;t t
 s,@tclutil_BUILD_LIB_SPEC@,$tclutil_BUILD_LIB_SPEC,;t t
@@ -15009,6 +14983,39 @@ s,@skycat_BUILD_LIB_SPEC@,$skycat_BUILD_LIB_SPEC,;t t
 s,@skycat_BUILD_DIR@,$skycat_BUILD_DIR,;t t
 s,@skycat_LIB_SPEC@,$skycat_LIB_SPEC,;t t
 s,@skycat_SRC_DIR@,$skycat_SRC_DIR,;t t
+s,@PKG_SOURCES@,$PKG_SOURCES,;t t
+s,@PKG_OBJECTS@,$PKG_OBJECTS,;t t
+s,@CLEANFILES@,$CLEANFILES,;t t
+s,@TCL_INCLUDES@,$TCL_INCLUDES,;t t
+s,@TK_INCLUDES@,$TK_INCLUDES,;t t
+s,@TCL_THREADS@,$TCL_THREADS,;t t
+s,@SHARED_BUILD@,$SHARED_BUILD,;t t
+s,@AR@,$AR,;t t
+s,@CELIB_DIR@,$CELIB_DIR,;t t
+s,@LIBOBJS@,$LIBOBJS,;t t
+s,@SHLIB_SUFFIX@,$SHLIB_SUFFIX,;t t
+s,@DL_LIBS@,$DL_LIBS,;t t
+s,@CFLAGS_DEBUG@,$CFLAGS_DEBUG,;t t
+s,@CFLAGS_OPTIMIZE@,$CFLAGS_OPTIMIZE,;t t
+s,@CFLAGS_WARNING@,$CFLAGS_WARNING,;t t
+s,@STLIB_LD@,$STLIB_LD,;t t
+s,@SHLIB_LD@,$SHLIB_LD,;t t
+s,@SHLIB_CFLAGS@,$SHLIB_CFLAGS,;t t
+s,@SHLIB_LD_LIBS@,$SHLIB_LD_LIBS,;t t
+s,@LDFLAGS_DEBUG@,$LDFLAGS_DEBUG,;t t
+s,@LDFLAGS_OPTIMIZE@,$LDFLAGS_OPTIMIZE,;t t
+s,@LD_LIBRARY_PATH_VAR@,$LD_LIBRARY_PATH_VAR,;t t
+s,@TCL_DBGX@,$TCL_DBGX,;t t
+s,@CFLAGS_DEFAULT@,$CFLAGS_DEFAULT,;t t
+s,@LDFLAGS_DEFAULT@,$LDFLAGS_DEFAULT,;t t
+s,@MAKE_LIB@,$MAKE_LIB,;t t
+s,@MAKE_SHARED_LIB@,$MAKE_SHARED_LIB,;t t
+s,@MAKE_STATIC_LIB@,$MAKE_STATIC_LIB,;t t
+s,@MAKE_STUB_LIB@,$MAKE_STUB_LIB,;t t
+s,@RANLIB_STUB@,$RANLIB_STUB,;t t
+s,@TCLSH_PROG@,$TCLSH_PROG,;t t
+s,@WISH_PROG@,$WISH_PROG,;t t
+s,@OS@,$OS,;t t
 s,@SHLIB_LD_CXX_LIBS@,$SHLIB_LD_CXX_LIBS,;t t
 s,@STARLINK@,$STARLINK,;t t
 s,@STAR_CPPFLAGS@,$STAR_CPPFLAGS,;t t
