Regenerated files to use changed acx_prog_cc_optim (remove host tuning for Tru64 UNIX).
svn path=/trunk/; revision=18579

diff --git a/applications/extractor/sextractor/configure b/applications/extractor/sextractor/configure
--- a/applications/extractor/sextractor/configure
+++ b/applications/extractor/sextractor/configure
@@ -1,6 +1,6 @@
 #! /bin/sh
 # Guess values for system-dependent variables and create Makefiles.
-# Generated by Starlink Autoconf 2.59 for sextractor 2.3.2.
+# Generated by Starlink Autoconf 2.59 for sextractor 2.4.3.
 #
 # Report bugs to <bertin@iap.fr>.
 #
@@ -269,8 +269,8 @@ SHELL=${CONFIG_SHELL-/bin/sh}
 # Identity of this package.
 PACKAGE_NAME='sextractor'
 PACKAGE_TARNAME='sextractor'
-PACKAGE_VERSION='2.3.2'
-PACKAGE_STRING='sextractor 2.3.2'
+PACKAGE_VERSION='2.4.3'
+PACKAGE_STRING='sextractor 2.4.3'
 PACKAGE_BUGREPORT='bertin@iap.fr'
 
 ac_unique_file="src/makeit.c"
@@ -780,7 +780,7 @@ if test "$ac_init_help" = "long"; then
   # Omit some internal or obsolete options to make the list less imposing.
   # This message is too long to be a string in the A/UX 3.1 sh.
   cat <<_ACEOF
-\`configure' configures sextractor 2.3.2 to adapt to many kinds of systems.
+\`configure' configures sextractor 2.4.3 to adapt to many kinds of systems.
 
 Usage: $0 [OPTION]... [VAR=VALUE]...
 
@@ -842,7 +842,7 @@ fi
 
 if test -n "$ac_init_help"; then
   case $ac_init_help in
-     short | recursive ) echo "Configuration of sextractor 2.3.2:";;
+     short | recursive ) echo "Configuration of sextractor 2.4.3:";;
    esac
   cat <<\_ACEOF
 
@@ -972,7 +972,7 @@ fi
 test -n "$ac_init_help" && exit 0
 if $ac_init_version; then
   cat <<\_ACEOF
-sextractor configure 2.3.2
+sextractor configure 2.4.3
 generated by Starlink Autoconf 2.59
 
 Copyright (C) 2003 Free Software Foundation, Inc.
@@ -986,7 +986,7 @@ cat >&5 <<_ACEOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
 
-It was created by sextractor $as_me 2.3.2, which was
+It was created by sextractor $as_me 2.4.3, which was
 generated by Starlink Autoconf 2.59.  Invocation command line was
 
   $ $0 $@
@@ -1608,7 +1608,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE='sextractor'
- VERSION='2.3.2'
+ VERSION='2.4.3'
 
 
 cat >>confdefs.h <<_ACEOF
@@ -1750,7 +1750,7 @@ DATE3="$date3"
 
 
 # Include macros
-#sinclude(acx_prog_cc_optim.m4)
+
 
 # Display pakage and version number
 echo "$as_me:$LINENO: result: *********** Configuring:  $PACKAGE $VERSION ($date) **********" >&5
@@ -3704,12 +3704,7 @@ if test "$ac_cv_search_strerror" != no; then
 fi
 
 
-  ansi=
-  if test -z "$ansi"; then
-    msg="for C compiler warning flags"
-  else
-    msg="for C compiler warning and ANSI conformance flags"
-  fi
+  msg="for C compiler optimization flags"
   echo "$as_me:$LINENO: checking $msg" >&5
 echo $ECHO_N "checking $msg... $ECHO_C" >&6
 if test "${prog_cc_optim_flags+set}" = set; then
@@ -3722,75 +3717,44 @@ int main(int argc, char **argv) { return 0; }
 EOF
 
             if test "$GCC" = "yes"; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O -ansi"
-        fi
+        prog_cc_optim_flags="-O3 -funroll-loops -fomit-frame-pointer -Wall"
 
 
             elif $CC -V 2>&1 | grep -i "WorkShop" > /dev/null 2>&1 &&
-           $CC -c -v -Xc conftest.c > /dev/null 2>&1 &&
+           $CC -c -O conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="-O"
 
-            elif $CC -V 2>&1 | grep -i "Digital UNIX Compiler" > /dev/null 2>&1 &&
-           $CC -c -verbose -w0 -warnprotos -std1 conftest.c > /dev/null 2>&1 &&
+            elif ($CC -V 2>&1 | grep -i "Digital UNIX Compiler"> /dev/null 2>&1 ||
+	   $CC -V 2>&1 | grep -i "Compaq C"> /dev/null 2>&1) &&
+           $CC -c -fast conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+         prog_cc_optim_flags="-fast"
 
             elif $CC 2>&1 | grep -i "C for AIX Compiler" > /dev/null 2>&1 &&
-           $CC -c -qlanglvl=ansi -qinfo=all conftest.c > /dev/null 2>&1 &&
+           $CC -c -qinfo=all -O2 conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="-O2"
 
             elif $CC -version 2>&1 | grep -i "MIPSpro Compilers" > /dev/null 2>&1 &&
-           $CC -c -fullwarn -ansi -ansiE conftest.c > /dev/null 2>&1 &&
+           $CC -c -fullwarn -O3 conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="-O3"
 
             elif what $CC 2>&1 | grep -i "HP C Compiler" > /dev/null 2>&1 &&
-           $CC -c -Aa +w1 conftest.c > /dev/null 2>&1 &&
+           $CC -c -Aa +O3 conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="+O3"
 
             elif $CC -V 2>&1 | grep "/SX" > /dev/null 2>&1 &&
-           $CC -c -pvctl,fullmsg -Xc conftest.c > /dev/null 2>&1 &&
+           $CC -c -Xc -O conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="-O"
 
             elif $CC -V 2>&1 | grep -i "Cray" > /dev/null 2>&1 &&
-           $CC -c -h msglevel 2 conftest.c > /dev/null 2>&1 &&
+           $CC -c -h conform -O3 conftest.c > /dev/null 2>&1 &&
            test -f conftest.o; then
-        if test -z "$ansi"; then
-          prog_cc_optim_flags="-O"
-        else
-          prog_cc_optim_flags="-O"
-        fi
+        prog_cc_optim_flags="-O3"
 
       fi
       rm -f conftest.*
@@ -5096,7 +5060,237 @@ esac
 
 fi
 
-#AC_FUNC_MALLOC
+
+for ac_header in stdlib.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_c_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_c_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## ---------------------------- ##
+## Report this to bertin@iap.fr ##
+## ---------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+fi
+
+done
+
+echo "$as_me:$LINENO: checking for GNU libc compatible malloc" >&5
+echo $ECHO_N "checking for GNU libc compatible malloc... $ECHO_C" >&6
+if test "${ac_cv_func_malloc_0_nonnull+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  ac_cv_func_malloc_0_nonnull=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#if STDC_HEADERS || HAVE_STDLIB_H
+# include <stdlib.h>
+#else
+char *malloc ();
+#endif
+
+int
+main ()
+{
+exit (malloc (0) ? 0 : 1);
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_func_malloc_0_nonnull=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+ac_cv_func_malloc_0_nonnull=no
+fi
+rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_func_malloc_0_nonnull" >&5
+echo "${ECHO_T}$ac_cv_func_malloc_0_nonnull" >&6
+if test $ac_cv_func_malloc_0_nonnull = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_MALLOC 1
+_ACEOF
+
+else
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_MALLOC 0
+_ACEOF
+
+   case $LIBOBJS in
+    "malloc.$ac_objext"   | \
+  *" malloc.$ac_objext"   | \
+    "malloc.$ac_objext "* | \
+  *" malloc.$ac_objext "* ) ;;
+  *) LIBOBJS="$LIBOBJS malloc.$ac_objext" ;;
+esac
+
+
+cat >>confdefs.h <<\_ACEOF
+#define malloc rpl_malloc
+_ACEOF
+
+fi
+
+
+
 
 
 for ac_header in stdlib.h unistd.h
@@ -6594,7 +6788,7 @@ if test "$use_gprof" = "yes"; then
   if test "$use_icc" = "yes"; then
     CFLAGS="$CFLAGS -pq"
   else
-    CFLAGS="$CFLAGS -pg"
+    CFLAGS="-O3 -pg"
   fi
   use_static="no"
 fi
@@ -6949,7 +7143,7 @@ _ASBOX
 } >&5
 cat >&5 <<_CSEOF
 
-This file was extended by sextractor $as_me 2.3.2, which was
+This file was extended by sextractor $as_me 2.4.3, which was
 generated by Starlink Autoconf 2.59.  Invocation command line was
 
   CONFIG_FILES    = $CONFIG_FILES
@@ -7012,7 +7206,7 @@ _ACEOF
 
 cat >>$CONFIG_STATUS <<_ACEOF
 ac_cs_version="\\
-sextractor config.status 2.3.2
+sextractor config.status 2.4.3
 configured by $0, generated by Starlink Autoconf 2.59,
   with options \\"`echo "$ac_configure_args" | sed 's/[\\""\`\$]/\\\\&/g'`\\"
 
