Don't fail if match isn't installed
svn path=/trunk/; revision=11060

diff --git a/applications/autoastrom/t/t7 b/applications/autoastrom/t/t7
--- a/applications/autoastrom/t/t7
+++ b/applications/autoastrom/t/t7
@@ -6,9 +6,17 @@ if test -z "$AUTOASTROM_DIR"; then
     echo "No AUTOASTROM_DIR -- autoastrom must be test-installed"
     exit 1
 fi
+if test ! -d $AUTOASTROM_DIR; then
+    echo "Can't find autoastrom directory $AUTOASTROM_DIR"
+    exit 1
+fi
 if test ! -x $AUTOASTROM_DIR/autoastrom; then
     echo "Can't find autoastrom script in directory $AUTOASTROM_DIR"
     exit 1
+fi
+if test ! -x $AUTOASTROM_DIR/match; then
+    echo "Match program isn't installed -- ignore this test"
+    exit 2
 fi
 
 
@@ -21,7 +29,6 @@ test -n "$KAPPA_DIR"		|| KAPPA_DIR=/star/bin/kappa
 # Need CCDPACK 4.0-1 and ATOOLS 1.3, so the following might need predefining
 test -n "$CCDPACK_DIR"		|| CCDPACK_DIR=/star/bin/ccdpack
 test -n "$ATOOLS_DIR"		|| ATOOLS_DIR=/star/bin/atools
-
 
 
 
