Rationalised (and incidentally updated) crazy regression test
svn path=/trunk/; revision=9164

diff --git a/applications/astrom/t/t1 b/applications/astrom/t/t1
--- a/applications/astrom/t/t1
+++ b/applications/astrom/t/t1
@@ -1,14 +1,15 @@
 #! /bin/sh -
 
 test -n "$RUN" || RUN=../astrom.x
-if ! make t1.run >&2; then
-    echo "Can't build t1.run"
+test -x fitsdump || make fitsdump >&2
+if test ! -x fitsdump; then
+    echo "Can't build fitsdump"
     exit 1
 fi
 
-cat >t1.astrom-in <<EOF
-* ASTROM input file generated by /home/norman/s/src/autoastrom/w/autoastrom/autoastrom.pl
-* Thu May 31 17:56:50 2001
+rm -f tmp1*
+
+cat >tmp1.astrom-in <<EOF
 J2000
 ASTR
 17 27  9.120   74 20  8.160   J2000  1998.47
@@ -31,17 +32,38 @@ ASTR
 END
 EOF
 
-$RUN . t1.astrom-in t1.rep t1.sum t1-fits t1.log
+
+$RUN . tmp1.astrom-in tmp1.rep tmp1.sum tmp1-fits tmp1.log
+
+
+for f in tmp1.astrom-in tmp1.rep tmp1.sum tmp1.log
+do
+    echo "!!!+ $f"
+    cat $f
+    echo "!!!-"
+done
+for f in tmp1-fits*
+do
+    echo "!!!+ $f"
+    ./fitsdump $f
+    echo "!!!-"
+done
+
+rm -f tmp1*
+
+exit 0
+
+
 
 testfailed=false
 
 # Strip DATE records from fits files (contains today's date)
-for f in *fits; do ./t1.run $f;done
+for f in *fits; do ./fitsdump $f > $f-ascii;done
 
-for f in t1.rep t1.sum t1-fits*fits t1.log
+for f in t1.rep t1.sum t1-fits*fits-ascii t1.log
 do
 	echo "Testing $f... "
-	cmp $f $f.correct
+	diff $f $f.correct >$f.diff
 	if [ $? = 0 ]; then
 		echo "ok"
 	else
